name: 🚀 CI/CD Simplificado

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  POSTGRES_VERSION: '13'

jobs:
  test:
    runs-on: ubuntu-latest
    # Executa em push para main, ou em PRs rotulados com 'run-tests'
    if: (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-tests'))
    continue-on-error: true
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cbmgo_test
        options: >
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
    
    - name: 🟢 Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: 📦 Install Backend Dependencies
      run: |
        cd backend
        npm ci
    
    - name: 📦 Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: ⚙️ Setup Test Environment
      run: |
        cd backend
        cp .env.example .env.test
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: cbmgo_test
        DB_USER: postgres
        DB_PASSWORD: postgres
        JWT_SECRET: test-secret-key
        JWT_EXPIRES_IN: 24h
        NODE_ENV: test
    
    - name: Run backend tests
      run: |
        cd backend
        npm test || true
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: cbmgo_test
        DB_USER: postgres
        DB_PASSWORD: postgres
        JWT_SECRET: test-secret-key
        JWT_EXPIRES_IN: 24h
        NODE_ENV: test
    
    # Cobertura e Codecov removidos para agilizar
    
    - name: 🏗️ Build Frontend
      run: |
        cd frontend
        npm run build
    
    - name: 🧪 Run Frontend Tests
      run: |
        cd frontend
        CI=true npm test -- --coverage --watchAll=false

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Run ESLint (Backend)
      run: |
        cd backend
        npx eslint . --ext .js --max-warnings 0
      continue-on-error: true
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run ESLint (Frontend)
      run: |
        cd frontend
        npx eslint src --ext .js,.jsx --max-warnings 0
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    # Executa em push para main, ou em PRs rotulados com 'run-tests'
    if: (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-tests'))
    continue-on-error: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Run security audit (Backend)
      run: |
        cd backend
        npm audit --audit-level moderate || true
    
    - name: Run security audit (Frontend)
      run: |
        cd frontend
        npm audit --audit-level high || true
      continue-on-error: true

  deploy:
    needs: [test, lint, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        cd ../frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Aqui você adicionaria os comandos específicos para deploy
        # Por exemplo: rsync, scp, docker build/push, etc.
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        # Aqui você adicionaria testes básicos para verificar se o deploy funcionou
        # Por exemplo: curl para verificar se a API está respondendo
    
    - name: Deploy to production
      if: success()
      run: |
        echo "Deploying to production environment..."
        # Comandos para deploy em produção
      env:
        PROD_DEPLOY_HOST: ${{ secrets.PROD_DEPLOY_HOST }}
        PROD_DEPLOY_USER: ${{ secrets.PROD_DEPLOY_USER }}
        PROD_DEPLOY_KEY: ${{ secrets.PROD_DEPLOY_KEY }}

  notify:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "✅ Deploy realizado com sucesso!"
        else
          echo "❌ Falha no deploy"
        fi
        # Aqui você pode adicionar notificações para Slack, Discord, email, etc.